/*
 * taskpriorities.h
 *
 *  Created on: 10 Jun 2021
 *      Author: visa
 */

#ifndef TASKPRIORITIES_H_
#define TASKPRIORITIES_H_

#define ADCTASKPRIORITY 3
#define CANTXTASKPRIORITY 8
#define CANRXTASKPRIORITY 7
#define ConfigTASKPRIORITY 2
#define DEBUGTASKPRIORITY 1
#define EEPROMTASKPRIORITY 1
#define INPUTTASKPRIORITY 3
#define INVTASKPRIORITY 3
#define LCDTASKPRIORITY 1
#define OUTPUTTASKPRIORITY 1
#define POWERTASKPRIORITY 3
#define WATCHDOGTASKPRIORITY 1

#define MAINTASKTASKPRIORITY 2

#endif /* TASKPRIORITIES_H_ */
